logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # RabbitMQ queue, exchange, routing-key ??
    queue:
      name: sample.queue
    exchange:
      name: sample.exchange
    routing:
      key: sample.key
  # mongodb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: log
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9191
